### PR TITLE
Handlers

### PR DESCRIPTION
**Pull request by camertron**
This PR moves hooks from app.rb into individual, testable classes. No real code changes here, just moving code to new files.

@jdoconnor @st33b @zvkemp

### CODE REVIEW

**Comment by matthewjackowski** [comment]
@camertron a big thanks for the refactors!  I'll take a quick looksee after tests run.  I'm finding that Travisci is running very slowly.  Is this your experience too?

**Comment by camertron** [comment]
Passing test run: https://travis-ci.org/lumoslabs/txgh/builds/101902061

**Comment by camertron** [comment]
No problem @matthewjackowski! I plan on submitting a few more, is that cool?

**Comment by st33b** [comment]
lgtm
+1 for swapping out double-quotes for single-quotes

**Comment by camertron** [comment]
@matthewjackowski I personally haven't noticed travis running slowly. We could try adding `sudo: false` to the config, which signals travis to run the tests on their new container-based infrastructure. Containerized builds are generally faster.

**Comment by matthewjackowski** [comment]
Note: tests passed on master

**Pull request merged**
