### PR TITLE
Multi-branch support

### PR DESCRIPTION
**Pull request by camertron**
This is an opt-in feature. Normally txgh pushes and pulls from a single branch, specified in the configuration. By specifying the special keyword `'all'` instead of a branch name, txgh will now process commits and upload resources for individual git branches. It does this by tagging each resource with the corresponding branch name using Transifex's categories feature. Each uploaded resource will have two categories, `branch:branch_name` and `author:First_Last`. Txgh uses the branch category to identify which git branch to push the finished translations to upon receiving a Transifex webhook request.

@jdoconnor @st33b @zvkemp

### CODE REVIEW

**Comment by matthewjackowski** [comment]
@camertron FYI...I am still reviewing this change...however I'm getting an error using the old branch configuration with the new code.  I want to make sure we don't break existing config setups with a updated master.

**Comment by camertron** [comment]
@matthewjackowski Can you point me to the error or provide a stack trace?

**Comment by matthewjackowski** [comment]
Here's the interesting bit on the transifex hook call I get: 
016-02-02T19:18:33.994464+00:00 app[web.1]: 2016-02-02 19:18:33 - Octokit::NotFound - POST https://api.github.com/repos/matthewjackowski/txgh-test-resources/git/blobs: 404 - Not Found // See: https://developer.github.com/v3:

Full disclaimer...I still haven't ruled out a config issue (unit tests pass on this same server).  I'm writing a test to be able to reproduce.

**Comment by camertron** [comment]
Hmm... this might happen if you have the wrong credentials configured. Do you have all the right environment variables set?

**Comment by matthewjackowski** [comment]
My issue was around token scoping in Github.  Ok to merge.

**Pull request merged**
